<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['port_forwarding_app_description'] = 'Приложение "Перенаправление портов" позволяет разрешить доступ к системе в вашей локальной сети из Интернета.';
$lang['port_forwarding_app_name'] = 'Перенаправление портов';
$lang['port_forwarding_feature_is_not_supported'] = 'Функция не поддерживается.';
$lang['port_forwarding_port_forwarding'] = 'Перенаправление портов';
$lang['port_forwarding_port_range_warning'] = 'Диапазоны портов должны быть указаны с использованием одного порта (например, 15000) и окончание портов (например, 15999).';
