<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['port_forwarding_app_description'] = 'The Port Forwarding app makes it possible to allow access to systems on your local network from the Internet.';
$lang['port_forwarding_app_name'] = 'Port Forwarding';
$lang['port_forwarding_port_forwarding'] = 'Port Forwarding';
