<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['port_forwarding_app_description'] = 'Appen för vidarebefordran av port ger möjligheten att tillåta åtkomst till system på ditt lokala nätverk från Internet.';
$lang['port_forwarding_app_name'] = 'Vidarebefordran av port';
$lang['port_forwarding_port_forwarding'] = 'Vidarebefordran av port';
