<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['port_forwarding_app_description'] = 'Appen för vidarebefordran av port ger möjligheten att tillåta åtkomst till system på ditt lokala nätverk från Internet.';
$lang['port_forwarding_app_name'] = 'Vidarebefordran av port';
$lang['port_forwarding_feature_is_not_supported'] = 'Feature is not supported.';
$lang['port_forwarding_port_forwarding'] = 'Vidarebefordran av port';
$lang['port_forwarding_port_range_warning'] = 'Port ranges must be specified using a single port start (eg. 15000) to a single port end (eg. 15999).';
