<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['port_forwarding_app_description'] = 'Aplikacja przekierowania portów pozwala na dostępu do systemów w Twojej sieci poprzez Internet.';
$lang['port_forwarding_app_name'] = 'Przekierowanie portów';
$lang['port_forwarding_port_forwarding'] = 'Przekierowanie portów';
