<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['port_forwarding_app_description'] = 'Aplikacja przekierowania portów pozwala na dostępu do systemów w Twojej sieci poprzez Internet.';
$lang['port_forwarding_app_name'] = 'Przekierowanie portów';
$lang['port_forwarding_feature_is_not_supported'] = 'Feature is not supported.';
$lang['port_forwarding_port_forwarding'] = 'Przekierowanie portów';
$lang['port_forwarding_port_range_warning'] = 'Port ranges must be specified using a single port start (eg. 15000) to a single port end (eg. 15999).';
