<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['port_forwarding_app_description'] = 'Aplikacja przekierowania portów pozwala na dostępu do systemów w Twojej sieci poprzez Internet.';
$lang['port_forwarding_app_name'] = 'Przekierowanie portów';
$lang['port_forwarding_feature_is_not_supported'] = 'Funkcja nie jest obsługiwana.';
$lang['port_forwarding_port_forwarding'] = 'Przekierowanie portów';
$lang['port_forwarding_port_range_warning'] = 'Zakres portów musi być określony używając pojedynczego portu początkowego (np. 15000) oraz pojedynczego portu końcowego (np. 15999).';
